"""Compare synthetic FENIKS DSPS-closure catalogs to a z<=0.35 reference set."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Sequence

import numpy as np
import pandas as pd

from euclid_dsps.io import ensure_dir
from euclid_dsps.parameters import DIFFSKY_BASIC_PARAMETER_NAMES
from euclid_dsps.photometry import fnu_cgs_to_abmag


DEFAULT_BANDS = (
    "lsst_u",
    "lsst_g",
    "lsst_r",
    "lsst_i",
    "lsst_z",
    "lsst_y",
    "roman_F062",
    "roman_F087",
    "roman_F106",
    "roman_F129",
    "roman_F146",
    "roman_F158",
    "roman_F184",
    "roman_F213",
)

FS2_REFERENCE_ALIASES = {
    "redshift_true": "z_true_gal",
    "logsfr_true": "log_sfr_true",
    "dust_av": "dust_ebv_true",
}

FS2_FNU_CGS_BANDS = (
    "lsst_u",
    "lsst_g",
    "lsst_r",
    "lsst_i",
    "lsst_z",
    "lsst_y",
    "euclid_vis",
    "euclid_nisp_y",
    "euclid_nisp_j",
    "euclid_nisp_h",
)

LATENT_COLUMN_PAIRS = (
    ("redshift", "redshift_true", "redshift_true"),
    ("logsm", "logsm_true", "logsm_true"),
    ("logsfr", "logsfr_true", "logsfr_true"),
    ("logssfr", "logssfr_true", "logssfr_true"),
    ("logmp", "logmp_true", "logmp_true"),
    ("logmp0", "logmp0_true", "diffmah_logmp0"),
    ("central", "central_true", "central_true"),
    ("diffstar_lgmcrit", "diffstar_lgmcrit_true", "diffstar_lgmcrit"),
    ("diffstar_lgy_at_mcrit", "diffstar_lgy_at_mcrit_true", "diffstar_lgy_at_mcrit"),
    ("diffstar_indx_lo", "diffstar_indx_lo_true", "diffstar_indx_lo"),
    ("diffstar_indx_hi", "diffstar_indx_hi_true", "diffstar_indx_hi"),
    ("diffstar_lg_qt", "diffstar_lg_qt_true", "diffstar_lg_qt"),
    ("diffstar_qlglgdt", "diffstar_qlglgdt_true", "diffstar_qlglgdt"),
    ("diffstar_lg_drop", "diffstar_lg_drop_true", "diffstar_lg_drop"),
    ("diffstar_lg_rejuv", "diffstar_lg_rejuv_true", "diffstar_lg_rejuv"),
    ("diffmah_logm0", "diffmah_logm0_true", "diffmah_logm0"),
    ("diffmah_logtc", "diffmah_logtc_true", "diffmah_logtc"),
    ("diffmah_early_index", "diffmah_early_index_true", "diffmah_early_index"),
    ("diffmah_late_index", "diffmah_late_index_true", "diffmah_late_index"),
    ("diffmah_t_peak", "diffmah_t_peak_true", "diffmah_t_peak"),
    (
        "log10_stellar_metallicity",
        "log10_stellar_metallicity_true",
        "log10_stellar_metallicity",
    ),
    ("dust_av", "dust_av_true", "dust_av"),
    ("dust_delta", "dust_delta_true", "dust_delta"),
)

COLOR_PAIRS = (
    ("lsst_u", "lsst_g"),
    ("lsst_g", "lsst_r"),
    ("lsst_r", "lsst_i"),
    ("lsst_i", "lsst_z"),
    ("lsst_z", "lsst_y"),
    ("roman_F062", "roman_F087"),
    ("roman_F087", "roman_F106"),
    ("roman_F106", "roman_F158"),
    ("roman_F158", "roman_F213"),
    ("euclid_vis", "euclid_nisp_y"),
    ("euclid_nisp_y", "euclid_nisp_j"),
    ("euclid_nisp_j", "euclid_nisp_h"),
)

COLOR_COLOR_PLOTS = (
    ("lsst_u", "lsst_g", "lsst_r"),
    ("lsst_g", "lsst_r", "lsst_i"),
    ("lsst_r", "lsst_i", "lsst_z"),
    ("lsst_i", "lsst_z", "lsst_y"),
    ("roman_F062", "roman_F087", "roman_F106"),
    ("roman_F087", "roman_F106", "roman_F129"),
    ("roman_F106", "roman_F129", "roman_F158"),
    ("roman_F129", "roman_F158", "roman_F184"),
    ("roman_F158", "roman_F184", "roman_F213"),
    ("euclid_vis", "euclid_nisp_y", "euclid_nisp_j"),
    ("euclid_nisp_y", "euclid_nisp_j", "euclid_nisp_h"),
)

REFERENCE_DOT_COLOR = "black"
SYNTHETIC_DOT_COLOR = "#00a846"


def compare_synthetic_closure_to_reference(
    *,
    synthetic_path: str | Path,
    reference_path: str | Path,
    out_dir: str | Path,
    proposal_dir: str | Path | None = None,
    bands: Sequence[str] | None = None,
    max_reference: int | None = None,
    seed: int = 260617,
    plots: bool = True,
    reference_kind: str = "auto",
) -> dict[str, Path]:
    """Write population and photometry diagnostics for synthetic-vs-reference data.

    This is a population sanity comparison. The reference HLTDS photometry is
    Diffsky-generated, while the synthetic closure photometry is regenerated by
    euclid_dsps; the photometry metrics therefore diagnose gross consistency,
    not an exact closure equality.
    """
    synthetic_path = Path(synthetic_path)
    reference_path = Path(reference_path)
    out = ensure_dir(Path(out_dir))
    plot_dir = ensure_dir(out / "plots")
    band_names = tuple(bands or DEFAULT_BANDS)

    synthetic = pd.read_parquet(synthetic_path)
    reference = pd.read_parquet(reference_path)
    reference_kind = _infer_reference_kind(reference, reference_kind)
    reference = _standardize_reference_frame(reference, reference_kind)
    reference_label = _reference_display_name(reference_kind)
    if max_reference is not None and int(max_reference) > 0 and len(reference) > int(max_reference):
        reference = reference.sample(n=int(max_reference), random_state=int(seed))
    reference = reference.reset_index(drop=True)

    distribution_rows = _distribution_metrics(synthetic, reference)
    distribution_metrics = pd.DataFrame(distribution_rows)
    distribution_path = out / "distribution_metrics.csv"
    distribution_metrics.to_csv(distribution_path, index=False)

    photometry_rows = _photometry_metrics(synthetic, reference, band_names)
    photometry_metrics = pd.DataFrame(photometry_rows)
    photometry_path = out / "photometry_metrics.csv"
    photometry_metrics.to_csv(photometry_path, index=False)

    proposals = _load_proposals(Path(proposal_dir)) if proposal_dir else None
    proposal_metrics_path: Path | None = None
    proposal_metrics = pd.DataFrame()
    if proposals is not None:
        proposal_metrics = pd.DataFrame(_proposal_weighted_metrics(proposals))
        proposal_metrics_path = out / "proposal_weighted_metrics.csv"
        proposal_metrics.to_csv(proposal_metrics_path, index=False)

    correlation_payload = _correlation_report(synthetic, reference)
    correlation_path = out / "correlation_metrics.json"
    _write_json(correlation_path, correlation_payload)

    plot_paths: list[Path] = []
    if plots:
        plot_paths = _write_plots(
            synthetic,
            reference,
            distribution_metrics,
            photometry_metrics,
            plot_dir,
            reference_label=reference_label,
        )

    summary = _summary_payload(
        synthetic_path=synthetic_path,
        reference_path=reference_path,
        reference_kind=reference_kind,
        out_dir=out,
        synthetic=synthetic,
        reference=reference,
        bands=band_names,
        max_reference=max_reference,
        distribution_metrics=distribution_metrics,
        photometry_metrics=photometry_metrics,
        proposal_metrics=proposal_metrics,
        correlation_payload=correlation_payload,
        plot_paths=plot_paths,
        reference_label=reference_label,
    )
    summary_path = out / "comparison_summary.json"
    _write_json(summary_path, summary)

    report_path = out / "report.md"
    report_path.write_text(_markdown_report(summary), encoding="utf-8")
    return {
        "summary": summary_path,
        "report": report_path,
        "distribution_metrics": distribution_path,
        "photometry_metrics": photometry_path,
        "correlation_metrics": correlation_path,
        **({"proposal_weighted_metrics": proposal_metrics_path} if proposal_metrics_path else {}),
    }


def _distribution_metrics(
    synthetic: pd.DataFrame,
    reference: pd.DataFrame,
) -> list[dict[str, Any]]:
    rows = []
    for quantity, synthetic_column, reference_column in LATENT_COLUMN_PAIRS:
        rows.append(
            _metric_row_from_columns(
                "latent",
                quantity,
                synthetic,
                reference,
                synthetic_column,
                reference_column,
            )
        )
    return rows


def _infer_reference_kind(reference: pd.DataFrame, requested: str) -> str:
    requested = str(requested or "auto").lower()
    if requested != "auto":
        return requested
    columns = set(reference.columns)
    if {"z_true_gal", "log_stellar_mass", "lsst_u"} <= columns:
        return "fs2"
    return "hltds"


def _reference_display_name(reference_kind: str) -> str:
    kind = str(reference_kind or "reference").lower()
    if kind == "fs2":
        return "Euclid FS2 phz1"
    if kind == "hltds":
        return "HLTDS z<=0.35 reference"
    return f"{reference_kind} reference"


def _standardize_reference_frame(
    reference: pd.DataFrame,
    reference_kind: str,
) -> pd.DataFrame:
    if str(reference_kind).lower() != "fs2":
        return reference
    frame = reference.copy()
    if "redshift_true" not in frame and "z_true_gal" in frame:
        frame["redshift_true"] = pd.to_numeric(frame["z_true_gal"], errors="coerce")
    if "logsm_true" not in frame and "log_stellar_mass" in frame:
        frame["logsm_true"] = (
            pd.to_numeric(frame["log_stellar_mass"], errors="coerce")
            + 2.0 * np.log10(0.73)
        )
    if "logsfr_true" not in frame and "log_sfr_true" in frame:
        frame["logsfr_true"] = pd.to_numeric(frame["log_sfr_true"], errors="coerce")
    if "logssfr_true" not in frame and {"logsfr_true", "logsm_true"} <= set(frame.columns):
        frame["logssfr_true"] = frame["logsfr_true"] - frame["logsm_true"]
    if "dust_av" not in frame and "dust_ebv_true" in frame:
        frame["dust_av"] = 4.05 * pd.to_numeric(frame["dust_ebv_true"], errors="coerce")
    if "log10_stellar_metallicity" not in frame and "metallicity_true" in frame:
        frame["log10_stellar_metallicity"] = (
            pd.to_numeric(frame["metallicity_true"], errors="coerce") - 10.61
        )
    for band in FS2_FNU_CGS_BANDS:
        if band not in frame.columns:
            continue
        raw_flux = pd.to_numeric(frame[band], errors="coerce").to_numpy(dtype=float)
        if f"flux_{band}" not in frame.columns:
            frame[f"flux_{band}"] = raw_flux
        if f"mag_{band}" not in frame.columns:
            with np.errstate(divide="ignore", invalid="ignore"):
                mag = np.asarray(fnu_cgs_to_abmag(raw_flux), dtype=float)
            mag[~np.isfinite(raw_flux) | (raw_flux <= 0.0)] = np.nan
            frame[f"mag_{band}"] = mag
    return frame


def _reference_mag_column(reference: pd.DataFrame, band: str) -> str | None:
    for column in (f"mag_{band}", band, f"{band}_mag"):
        if column in reference.columns:
            return column
    return None


def _reference_flux_column(reference: pd.DataFrame, band: str) -> str | None:
    for column in (f"flux_{band}", f"{band}_flux"):
        if column in reference.columns:
            return column
    return None


def _reference_fluxerr_column(reference: pd.DataFrame, band: str) -> str | None:
    for column in (f"fluxerr_{band}", f"{band}_fluxerr", f"{band}_error"):
        if column in reference.columns:
            return column
    return None


def _reference_mask_column(reference: pd.DataFrame, band: str) -> str | None:
    for column in (f"mask_{band}", f"{band}_mask"):
        if column in reference.columns:
            return column
    return None


def _photometry_metrics(
    synthetic: pd.DataFrame,
    reference: pd.DataFrame,
    bands: Sequence[str],
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for band in bands:
        ref_mag_col = _reference_mag_column(reference, band)
        ref_flux_col = _reference_flux_column(reference, band)
        ref_err_col = _reference_fluxerr_column(reference, band)
        ref_mask_col = _reference_mask_column(reference, band)
        rows.append(
            _metric_row_from_columns(
                "mag_true_vs_reference_mag",
                band,
                synthetic,
                reference,
                f"mag_true_{band}",
                ref_mag_col or f"mag_{band}",
            )
        )
        rows.append(
            _metric_row_from_columns(
                "flux_true_vs_reference_flux",
                band,
                synthetic,
                reference,
                f"flux_true_{band}",
                ref_flux_col or f"flux_{band}",
            )
        )
        rows.append(
            _metric_row_from_columns(
                "flux_noisy_vs_reference_flux",
                band,
                synthetic,
                reference,
                f"flux_{band}",
                ref_flux_col or f"flux_{band}",
            )
        )
        rows.append(
            _metric_row_from_columns(
                "fluxerr",
                band,
                synthetic,
                reference,
                f"fluxerr_{band}",
                ref_err_col or f"fluxerr_{band}",
            )
        )
        rows.append(
            _metric_row_from_columns(
                "mask_fraction",
                band,
                synthetic,
                reference,
                f"mask_{band}",
                ref_mask_col or f"mask_{band}",
            )
        )
        syn_snr = _ratio_from_columns(synthetic, f"flux_{band}", f"fluxerr_{band}")
        ref_snr = (
            _ratio_from_columns(reference, ref_flux_col, ref_err_col)
            if ref_flux_col and ref_err_col
            else np.asarray([], dtype=float)
        )
        rows.append(
            _metric_row_from_arrays(
                "snr_observed",
                band,
                syn_snr,
                ref_snr,
                f"flux_{band}/fluxerr_{band}",
                (
                    f"{ref_flux_col}/{ref_err_col}"
                    if ref_flux_col and ref_err_col
                    else f"flux_{band}/fluxerr_{band}"
                ),
            )
        )
    for left, right in COLOR_PAIRS:
        if left not in bands or right not in bands:
            continue
        syn_color = _difference_from_columns(
            synthetic,
            f"mag_true_{left}",
            f"mag_true_{right}",
        )
        ref_left = _reference_mag_column(reference, left)
        ref_right = _reference_mag_column(reference, right)
        ref_color = (
            _difference_from_columns(reference, ref_left, ref_right)
            if ref_left and ref_right
            else np.asarray([], dtype=float)
        )
        rows.append(
            _metric_row_from_arrays(
                "color_true_vs_reference_color",
                f"{left}-{right}",
                syn_color,
                ref_color,
                f"mag_true_{left}-mag_true_{right}",
                f"{ref_left}-{ref_right}" if ref_left and ref_right else f"mag_{left}-mag_{right}",
            )
        )
    return rows


def _load_proposals(proposal_dir: Path) -> pd.DataFrame | None:
    if not proposal_dir.exists():
        return None
    paths = sorted(proposal_dir.glob("*/*.parquet"))
    if not paths:
        paths = sorted(proposal_dir.glob("*.parquet"))
    if not paths:
        return None
    return pd.concat([pd.read_parquet(path) for path in paths], ignore_index=True)


def _proposal_weighted_metrics(proposals: pd.DataFrame) -> list[dict[str, Any]]:
    if "galaxy_weight" not in proposals.columns:
        return []
    weights = _finite_numeric(proposals["galaxy_weight"])
    rows: list[dict[str, Any]] = []
    for quantity, column in (
        ("redshift", "redshift_true"),
        ("logsm", "logsm_true"),
        ("logsfr", "logsfr_true"),
        ("logssfr", "logssfr_true"),
        ("logmp", "logmp_true"),
        ("logmp0", "logmp0_true"),
        ("dust_av", "dust_av_true"),
        ("dust_delta", "dust_delta_true"),
        ("log10_stellar_metallicity", "log10_stellar_metallicity_true"),
    ):
        if column not in proposals.columns:
            continue
        values = pd.to_numeric(proposals[column], errors="coerce").to_numpy(dtype=float)
        raw_weights = pd.to_numeric(proposals["galaxy_weight"], errors="coerce").to_numpy(
            dtype=float
        )
        finite = np.isfinite(values) & np.isfinite(raw_weights) & (raw_weights > 0.0)
        values = values[finite]
        raw_weights = raw_weights[finite]
        row: dict[str, Any] = {
            "quantity": quantity,
            "column": column,
            "n": int(values.size),
            "weight_sum": float(np.sum(raw_weights)) if values.size else np.nan,
        }
        row.update(_prefixed_stats("unweighted", values))
        row.update(_weighted_stats("weighted", values, raw_weights))
        if quantity == "logsm":
            for threshold in (5.0, 7.0, 8.0, 9.0, 10.0):
                row[f"unweighted_fraction_ge_{threshold:g}"] = float(
                    np.mean(values >= threshold)
                )
                row[f"weighted_fraction_ge_{threshold:g}"] = float(
                    np.sum(raw_weights[values >= threshold]) / np.sum(raw_weights)
                )
        rows.append(row)
    return rows


def _weighted_stats(prefix: str, values: np.ndarray, weights: np.ndarray) -> dict[str, float]:
    values = _finite_array(values)
    weights = _finite_array(weights)
    n = min(values.size, weights.size)
    values = values[:n]
    weights = weights[:n]
    finite = np.isfinite(values) & np.isfinite(weights) & (weights > 0.0)
    values = values[finite]
    weights = weights[finite]
    if values.size == 0 or np.sum(weights) <= 0.0:
        return {
            f"{prefix}_mean": np.nan,
            f"{prefix}_q05": np.nan,
            f"{prefix}_q16": np.nan,
            f"{prefix}_median": np.nan,
            f"{prefix}_q84": np.nan,
            f"{prefix}_q95": np.nan,
        }
    return {
        f"{prefix}_mean": float(np.sum(values * weights) / np.sum(weights)),
        f"{prefix}_q05": float(_weighted_quantile(values, weights, 0.05)),
        f"{prefix}_q16": float(_weighted_quantile(values, weights, 0.16)),
        f"{prefix}_median": float(_weighted_quantile(values, weights, 0.5)),
        f"{prefix}_q84": float(_weighted_quantile(values, weights, 0.84)),
        f"{prefix}_q95": float(_weighted_quantile(values, weights, 0.95)),
    }


def _weighted_quantile(values: np.ndarray, weights: np.ndarray, quantile: float) -> float:
    order = np.argsort(values)
    values = values[order]
    weights = weights[order]
    cumulative = np.cumsum(weights)
    if cumulative[-1] <= 0.0:
        return np.nan
    cumulative = cumulative / cumulative[-1]
    return float(values[np.searchsorted(cumulative, float(quantile), side="left")])


def _metric_row_from_columns(
    group: str,
    quantity: str,
    synthetic: pd.DataFrame,
    reference: pd.DataFrame,
    synthetic_column: str,
    reference_column: str,
) -> dict[str, Any]:
    if synthetic_column not in synthetic.columns or reference_column not in reference.columns:
        return _missing_row(
            group,
            quantity,
            synthetic_column,
            reference_column,
            synthetic_column in synthetic.columns,
            reference_column in reference.columns,
        )
    return _metric_row_from_arrays(
        group,
        quantity,
        _finite_numeric(synthetic[synthetic_column]),
        _finite_numeric(reference[reference_column]),
        synthetic_column,
        reference_column,
    )


def _metric_row_from_arrays(
    group: str,
    quantity: str,
    synthetic_values: np.ndarray,
    reference_values: np.ndarray,
    synthetic_column: str,
    reference_column: str,
) -> dict[str, Any]:
    synthetic_values = _finite_array(synthetic_values)
    reference_values = _finite_array(reference_values)
    status = "ok"
    if synthetic_values.size < 2 or reference_values.size < 2:
        status = "insufficient_finite"
    row: dict[str, Any] = {
        "group": group,
        "quantity": quantity,
        "synthetic_column": synthetic_column,
        "reference_column": reference_column,
        "status": status,
        "synthetic_n": int(synthetic_values.size),
        "reference_n": int(reference_values.size),
    }
    row.update(_prefixed_stats("synthetic", synthetic_values))
    row.update(_prefixed_stats("reference", reference_values))
    row["delta_mean"] = _delta(row.get("synthetic_mean"), row.get("reference_mean"))
    row["delta_median"] = _delta(
        row.get("synthetic_median"),
        row.get("reference_median"),
    )
    if status == "ok":
        row["ks"] = float(_ks_distance(synthetic_values, reference_values))
        row["wasserstein_quantile"] = float(
            _wasserstein_quantile(synthetic_values, reference_values)
        )
    else:
        row["ks"] = np.nan
        row["wasserstein_quantile"] = np.nan
    return row


def _missing_row(
    group: str,
    quantity: str,
    synthetic_column: str,
    reference_column: str,
    has_synthetic: bool,
    has_reference: bool,
) -> dict[str, Any]:
    if not has_synthetic and not has_reference:
        status = "missing_both"
    elif not has_synthetic:
        status = "missing_synthetic"
    else:
        status = "missing_reference"
    row: dict[str, Any] = {
        "group": group,
        "quantity": quantity,
        "synthetic_column": synthetic_column,
        "reference_column": reference_column,
        "status": status,
        "synthetic_n": 0,
        "reference_n": 0,
        "ks": np.nan,
        "wasserstein_quantile": np.nan,
        "delta_mean": np.nan,
        "delta_median": np.nan,
    }
    row.update(_prefixed_stats("synthetic", np.asarray([], dtype=float)))
    row.update(_prefixed_stats("reference", np.asarray([], dtype=float)))
    return row


def _prefixed_stats(prefix: str, values: np.ndarray) -> dict[str, float]:
    if values.size == 0:
        return {
            f"{prefix}_mean": np.nan,
            f"{prefix}_std": np.nan,
            f"{prefix}_min": np.nan,
            f"{prefix}_q01": np.nan,
            f"{prefix}_q05": np.nan,
            f"{prefix}_q16": np.nan,
            f"{prefix}_median": np.nan,
            f"{prefix}_q84": np.nan,
            f"{prefix}_q95": np.nan,
            f"{prefix}_q99": np.nan,
            f"{prefix}_max": np.nan,
        }
    quantiles = np.quantile(values, [0.01, 0.05, 0.16, 0.5, 0.84, 0.95, 0.99])
    return {
        f"{prefix}_mean": float(np.mean(values)),
        f"{prefix}_std": float(np.std(values)),
        f"{prefix}_min": float(np.min(values)),
        f"{prefix}_q01": float(quantiles[0]),
        f"{prefix}_q05": float(quantiles[1]),
        f"{prefix}_q16": float(quantiles[2]),
        f"{prefix}_median": float(quantiles[3]),
        f"{prefix}_q84": float(quantiles[4]),
        f"{prefix}_q95": float(quantiles[5]),
        f"{prefix}_q99": float(quantiles[6]),
        f"{prefix}_max": float(np.max(values)),
    }


def _delta(left: Any, right: Any) -> float:
    try:
        left_value = float(left)
        right_value = float(right)
    except (TypeError, ValueError):
        return np.nan
    if not np.isfinite(left_value) or not np.isfinite(right_value):
        return np.nan
    return left_value - right_value


def _finite_numeric(series: pd.Series) -> np.ndarray:
    if pd.api.types.is_bool_dtype(series):
        arr = series.astype(float).to_numpy()
    else:
        arr = pd.to_numeric(series, errors="coerce").to_numpy(dtype=float)
    return _finite_array(arr)


def _finite_array(values: Iterable[float] | np.ndarray) -> np.ndarray:
    arr = np.asarray(values, dtype=float).reshape(-1)
    return arr[np.isfinite(arr)]


def _ratio_from_columns(frame: pd.DataFrame, numerator: str, denominator: str) -> np.ndarray:
    if numerator not in frame.columns or denominator not in frame.columns:
        return np.asarray([], dtype=float)
    num = pd.to_numeric(frame[numerator], errors="coerce").to_numpy(dtype=float)
    den = pd.to_numeric(frame[denominator], errors="coerce").to_numpy(dtype=float)
    finite = np.isfinite(num) & np.isfinite(den)
    if not np.any(finite):
        return np.asarray([], dtype=float)
    with np.errstate(divide="ignore", invalid="ignore"):
        return _finite_array(num[finite] / den[finite])


def _difference_from_columns(frame: pd.DataFrame, left: str, right: str) -> np.ndarray:
    if left not in frame.columns or right not in frame.columns:
        return np.asarray([], dtype=float)
    left_values = pd.to_numeric(frame[left], errors="coerce").to_numpy(dtype=float)
    right_values = pd.to_numeric(frame[right], errors="coerce").to_numpy(dtype=float)
    return _finite_array(left_values - right_values)


def _ks_distance(left: np.ndarray, right: np.ndarray) -> float:
    left = np.sort(_finite_array(left))
    right = np.sort(_finite_array(right))
    if left.size == 0 or right.size == 0:
        return np.nan
    values = np.sort(np.concatenate([left, right]))
    left_cdf = np.searchsorted(left, values, side="right") / left.size
    right_cdf = np.searchsorted(right, values, side="right") / right.size
    return float(np.max(np.abs(left_cdf - right_cdf)))


def _wasserstein_quantile(left: np.ndarray, right: np.ndarray, n_grid: int = 1001) -> float:
    left = _finite_array(left)
    right = _finite_array(right)
    if left.size == 0 or right.size == 0:
        return np.nan
    q = np.linspace(0.0, 1.0, int(n_grid))
    return float(np.mean(np.abs(np.quantile(left, q) - np.quantile(right, q))))


def _correlation_report(
    synthetic: pd.DataFrame,
    reference: pd.DataFrame,
) -> dict[str, Any]:
    labels: list[str] = []
    synthetic_columns: list[str] = []
    reference_columns: list[str] = []
    for quantity, synthetic_column, reference_column in LATENT_COLUMN_PAIRS:
        if synthetic_column in synthetic.columns and reference_column in reference.columns:
            syn_values = _finite_numeric(synthetic[synthetic_column])
            ref_values = _finite_numeric(reference[reference_column])
            if syn_values.size >= 3 and ref_values.size >= 3:
                labels.append(quantity)
                synthetic_columns.append(synthetic_column)
                reference_columns.append(reference_column)
    if len(labels) < 2:
        return {
            "status": "insufficient_columns",
            "labels": labels,
            "correlation_frobenius_error": np.nan,
        }
    syn_matrix = _finite_matrix(synthetic, synthetic_columns)
    ref_matrix = _finite_matrix(reference, reference_columns)
    if syn_matrix.shape[0] < 3 or ref_matrix.shape[0] < 3:
        return {
            "status": "insufficient_rows",
            "labels": labels,
            "synthetic_rows": int(syn_matrix.shape[0]),
            "reference_rows": int(ref_matrix.shape[0]),
            "correlation_frobenius_error": np.nan,
        }
    nonconstant = (np.std(syn_matrix, axis=0) > 0.0) & (
        np.std(ref_matrix, axis=0) > 0.0
    )
    if np.count_nonzero(nonconstant) < 2:
        return {
            "status": "insufficient_nonconstant_columns",
            "labels": labels,
            "synthetic_rows": int(syn_matrix.shape[0]),
            "reference_rows": int(ref_matrix.shape[0]),
            "correlation_frobenius_error": np.nan,
        }
    labels = [label for label, keep in zip(labels, nonconstant, strict=True) if keep]
    synthetic_columns = [
        column for column, keep in zip(synthetic_columns, nonconstant, strict=True) if keep
    ]
    reference_columns = [
        column for column, keep in zip(reference_columns, nonconstant, strict=True) if keep
    ]
    syn_matrix = syn_matrix[:, nonconstant]
    ref_matrix = ref_matrix[:, nonconstant]
    syn_corr = np.corrcoef(syn_matrix, rowvar=False)
    ref_corr = np.corrcoef(ref_matrix, rowvar=False)
    diff = syn_corr - ref_corr
    return {
        "status": "ok",
        "labels": labels,
        "synthetic_columns": synthetic_columns,
        "reference_columns": reference_columns,
        "synthetic_rows": int(syn_matrix.shape[0]),
        "reference_rows": int(ref_matrix.shape[0]),
        "correlation_frobenius_error": float(np.linalg.norm(diff)),
        "correlation_mean_abs_error": float(np.mean(np.abs(diff))),
        "synthetic_correlation": syn_corr,
        "reference_correlation": ref_corr,
        "correlation_difference": diff,
    }


def _finite_matrix(frame: pd.DataFrame, columns: Sequence[str]) -> np.ndarray:
    data = frame.loc[:, list(columns)].apply(pd.to_numeric, errors="coerce")
    matrix = data.to_numpy(dtype=float)
    finite = np.isfinite(matrix).all(axis=1)
    return matrix[finite]


def _write_plots(
    synthetic: pd.DataFrame,
    reference: pd.DataFrame,
    distribution_metrics: pd.DataFrame,
    photometry_metrics: pd.DataFrame,
    plot_dir: Path,
    *,
    reference_label: str,
) -> list[Path]:
    try:
        import matplotlib.pyplot as plt
    except Exception:
        return []
    paths: list[Path] = []
    selected = [
        ("redshift", "redshift_true", "redshift_true"),
        ("logsm", "logsm_true", "logsm_true"),
        ("logssfr", "logssfr_true", "logssfr_true"),
        ("dust_av", "dust_av_true", "dust_av"),
        ("dust_delta", "dust_delta_true", "dust_delta"),
    ]
    for label, syn_col, ref_col in selected:
        path = _hist_plot(
            plt,
            synthetic,
            reference,
            syn_col,
            ref_col,
            label,
            plot_dir,
            reference_label=reference_label,
        )
        if path is not None:
            paths.append(path)
    for band in ("lsst_u", "lsst_g", "lsst_r", "lsst_i", "roman_F106", "roman_F158"):
        path = _hist_plot(
            plt,
            synthetic,
            reference,
            f"mag_true_{band}",
            f"mag_{band}",
            f"mag_{band}",
            plot_dir,
            reference_label=reference_label,
        )
        if path is not None:
            paths.append(path)
    top = _top_metric_rows(distribution_metrics, "ks", n=8)
    if top:
        path = _bar_plot(plt, top, "ks", "top_latent_ks", plot_dir)
        if path is not None:
            paths.append(path)
    top_phot = _top_metric_rows(
        photometry_metrics[photometry_metrics["group"] == "mag_true_vs_reference_mag"],
        "delta_median",
        n=8,
        absolute=True,
    )
    if top_phot:
        path = _bar_plot(plt, top_phot, "delta_median", "top_mag_median_offsets", plot_dir)
        if path is not None:
            paths.append(path)
    color_color_paths = _color_color_plots(
        plt,
        synthetic,
        reference,
        plot_dir,
        reference_label=reference_label,
    )
    paths.extend(color_color_paths)
    plt.close("all")
    return paths


def _color_color_plots(
    plt: Any,
    synthetic: pd.DataFrame,
    reference: pd.DataFrame,
    plot_dir: Path,
    *,
    reference_label: str,
) -> list[Path]:
    paths: list[Path] = []
    rows: list[tuple[str, str, np.ndarray, np.ndarray, np.ndarray, np.ndarray]] = []
    for left, middle, right in COLOR_COLOR_PLOTS:
        syn_x, syn_y = _color_color_arrays(
            synthetic,
            f"mag_true_{left}",
            f"mag_true_{middle}",
            f"mag_true_{right}",
        )
        ref_x, ref_y = _color_color_arrays(
            reference,
            _reference_mag_column(reference, left),
            _reference_mag_column(reference, middle),
            _reference_mag_column(reference, right),
        )
        if syn_x.size < 2 or ref_x.size < 2:
            continue
        x_label = f"{left}-{middle}"
        y_label = f"{middle}-{right}"
        rows.append((x_label, y_label, syn_x, syn_y, ref_x, ref_y))
        path = _color_color_single_plot(
            plt,
            plot_dir / f"color_color_{_slug(x_label)}__{_slug(y_label)}.png",
            x_label,
            y_label,
            syn_x,
            syn_y,
            ref_x,
            ref_y,
            reference_label=reference_label,
        )
        if path is not None:
            paths.append(path)
    panel = _color_color_panel_plot(
        plt,
        plot_dir,
        rows,
        reference_label=reference_label,
    )
    if panel is not None:
        paths.append(panel)
    return paths


def _color_color_arrays(
    frame: pd.DataFrame,
    left_col: str | None,
    middle_col: str | None,
    right_col: str | None,
) -> tuple[np.ndarray, np.ndarray]:
    if left_col is None or middle_col is None or right_col is None:
        return np.asarray([], dtype=float), np.asarray([], dtype=float)
    if not {left_col, middle_col, right_col} <= set(frame.columns):
        return np.asarray([], dtype=float), np.asarray([], dtype=float)
    left = pd.to_numeric(frame[left_col], errors="coerce").to_numpy(dtype=float)
    middle = pd.to_numeric(frame[middle_col], errors="coerce").to_numpy(dtype=float)
    right = pd.to_numeric(frame[right_col], errors="coerce").to_numpy(dtype=float)
    x = left - middle
    y = middle - right
    finite = np.isfinite(x) & np.isfinite(y)
    return x[finite], y[finite]


def _color_color_single_plot(
    plt: Any,
    path: Path,
    x_label: str,
    y_label: str,
    syn_x: np.ndarray,
    syn_y: np.ndarray,
    ref_x: np.ndarray,
    ref_y: np.ndarray,
    *,
    reference_label: str,
) -> Path | None:
    if syn_x.size < 2 or ref_x.size < 2:
        return None
    syn_x, syn_y = _sample_xy(syn_x, syn_y, max_rows=25_000, seed=260617)
    ref_x, ref_y = _sample_xy(ref_x, ref_y, max_rows=50_000, seed=260618)
    fig, ax = plt.subplots(figsize=(5.2, 4.6))
    _draw_color_color_axes(
        ax,
        x_label,
        y_label,
        syn_x,
        syn_y,
        ref_x,
        ref_y,
        reference_label=reference_label,
    )
    ax.legend(frameon=False, loc="best", markerscale=2.0)
    fig.tight_layout()
    fig.savefig(path, dpi=180)
    plt.close(fig)
    return path


def _color_color_panel_plot(
    plt: Any,
    plot_dir: Path,
    rows: Sequence[tuple[str, str, np.ndarray, np.ndarray, np.ndarray, np.ndarray]],
    *,
    reference_label: str,
) -> Path | None:
    if not rows:
        return None
    ncols = 3
    nrows = int(np.ceil(len(rows) / ncols))
    fig, axes = plt.subplots(
        nrows,
        ncols,
        figsize=(5.0 * ncols, 4.4 * nrows),
        squeeze=False,
    )
    axes_arr = np.asarray(axes).reshape(-1)
    for index, (ax, row) in enumerate(zip(axes_arr, rows, strict=False)):
        x_label, y_label, syn_x, syn_y, ref_x, ref_y = row
        syn_x, syn_y = _sample_xy(syn_x, syn_y, max_rows=12_000, seed=260617 + index)
        ref_x, ref_y = _sample_xy(ref_x, ref_y, max_rows=24_000, seed=260717 + index)
        _draw_color_color_axes(
            ax,
            x_label,
            y_label,
            syn_x,
            syn_y,
            ref_x,
            ref_y,
            show_legend=index == 0,
            reference_label=reference_label,
        )
    for ax in axes_arr[len(rows):]:
        ax.axis("off")
    fig.tight_layout()
    path = plot_dir / "color_color_reference_black_synthetic_green.png"
    fig.savefig(path, dpi=180)
    plt.close(fig)
    return path


def _draw_color_color_axes(
    ax: Any,
    x_label: str,
    y_label: str,
    syn_x: np.ndarray,
    syn_y: np.ndarray,
    ref_x: np.ndarray,
    ref_y: np.ndarray,
    *,
    show_legend: bool = True,
    reference_label: str = "reference",
) -> None:
    ax.scatter(
        ref_x,
        ref_y,
        s=4,
        c=REFERENCE_DOT_COLOR,
        alpha=0.16,
        linewidths=0,
        rasterized=True,
        label=reference_label,
    )
    ax.scatter(
        syn_x,
        syn_y,
        s=7,
        c=SYNTHETIC_DOT_COLOR,
        alpha=0.55,
        linewidths=0,
        rasterized=True,
        label="FENIKS DSPS closure",
    )
    xlim = _robust_limits(np.concatenate([ref_x, syn_x]))
    ylim = _robust_limits(np.concatenate([ref_y, syn_y]))
    if xlim is not None:
        ax.set_xlim(*xlim)
    if ylim is not None:
        ax.set_ylim(*ylim)
    ax.set_xlabel(x_label)
    ax.set_ylabel(y_label)
    ax.grid(True, color="0.9", linewidth=0.7)
    if show_legend:
        ax.legend(frameon=False, loc="best", markerscale=2.0)


def _sample_xy(
    x: np.ndarray,
    y: np.ndarray,
    *,
    max_rows: int,
    seed: int,
) -> tuple[np.ndarray, np.ndarray]:
    n = min(x.size, y.size)
    x = np.asarray(x[:n], dtype=float)
    y = np.asarray(y[:n], dtype=float)
    finite = np.isfinite(x) & np.isfinite(y)
    x = x[finite]
    y = y[finite]
    if x.size <= int(max_rows):
        return x, y
    rng = np.random.default_rng(int(seed))
    idx = rng.choice(x.size, size=int(max_rows), replace=False)
    return x[idx], y[idx]


def _robust_limits(values: np.ndarray) -> tuple[float, float] | None:
    values = _finite_array(values)
    if values.size < 2:
        return None
    lo, hi = np.quantile(values, [0.005, 0.995])
    if not np.isfinite(lo) or not np.isfinite(hi) or lo == hi:
        return None
    pad = 0.08 * (hi - lo)
    return float(lo - pad), float(hi + pad)


def _hist_plot(
    plt: Any,
    synthetic: pd.DataFrame,
    reference: pd.DataFrame,
    synthetic_column: str,
    reference_column: str,
    label: str,
    plot_dir: Path,
    *,
    reference_label: str,
) -> Path | None:
    if synthetic_column not in synthetic.columns or reference_column not in reference.columns:
        return None
    syn = _finite_numeric(synthetic[synthetic_column])
    ref = _finite_numeric(reference[reference_column])
    if syn.size < 2 or ref.size < 2:
        return None
    fig, ax = plt.subplots(figsize=(6.0, 4.0))
    ax.hist(ref, bins=50, density=True, alpha=0.55, label=reference_label)
    ax.hist(syn, bins=min(30, max(5, syn.size // 2)), density=True, alpha=0.65, label="FENIKS closure")
    ax.set_xlabel(label)
    ax.set_ylabel("density")
    ax.legend(frameon=False)
    fig.tight_layout()
    path = plot_dir / f"{_slug(label)}.png"
    fig.savefig(path, dpi=150)
    plt.close(fig)
    return path


def _bar_plot(
    plt: Any,
    rows: list[dict[str, Any]],
    metric: str,
    name: str,
    plot_dir: Path,
) -> Path | None:
    if not rows:
        return None
    labels = [str(row["quantity"]) for row in rows]
    values = [float(row[metric]) for row in rows]
    fig, ax = plt.subplots(figsize=(8.0, 4.0))
    ax.bar(np.arange(len(values)), values)
    ax.set_xticks(np.arange(len(values)), labels, rotation=45, ha="right")
    ax.set_ylabel(metric)
    fig.tight_layout()
    path = plot_dir / f"{name}.png"
    fig.savefig(path, dpi=150)
    plt.close(fig)
    return path


def _top_metric_rows(
    frame: pd.DataFrame,
    metric: str,
    *,
    n: int,
    absolute: bool = False,
) -> list[dict[str, Any]]:
    if frame.empty or metric not in frame.columns:
        return []
    ok = frame[frame["status"] == "ok"].copy()
    ok = ok[np.isfinite(pd.to_numeric(ok[metric], errors="coerce"))]
    if ok.empty:
        return []
    score = pd.to_numeric(ok[metric], errors="coerce").abs() if absolute else pd.to_numeric(ok[metric], errors="coerce")
    ok = ok.assign(_score=score).sort_values("_score", ascending=False).head(int(n))
    return ok.drop(columns=["_score"]).to_dict(orient="records")


def _reference_photometry_units(
    reference: pd.DataFrame,
    bands: Sequence[str],
) -> dict[str, dict[str, Any]]:
    payload: dict[str, dict[str, Any]] = {}
    for band in bands:
        mag_column = _reference_mag_column(reference, band)
        flux_column = _reference_flux_column(reference, band)
        if not mag_column and not flux_column:
            continue
        payload[band] = {
            "mag_column": mag_column,
            "flux_column": flux_column,
            "mag_from_flux": bool(
                mag_column == f"mag_{band}"
                and flux_column == f"flux_{band}"
                and band in reference.columns
            ),
            "flux_units": "fnu_cgs" if flux_column else None,
            "mag_units": "AB" if mag_column else None,
        }
    return payload


def _summary_payload(
    *,
    synthetic_path: Path,
    reference_path: Path,
    reference_kind: str,
    out_dir: Path,
    synthetic: pd.DataFrame,
    reference: pd.DataFrame,
    bands: Sequence[str],
    max_reference: int | None,
    distribution_metrics: pd.DataFrame,
    photometry_metrics: pd.DataFrame,
    proposal_metrics: pd.DataFrame,
    correlation_payload: dict[str, Any],
    plot_paths: Sequence[Path],
    reference_label: str,
) -> dict[str, Any]:
    top_latent_ks = _top_metric_rows(distribution_metrics, "ks", n=10)
    top_latent_w1 = _top_metric_rows(distribution_metrics, "wasserstein_quantile", n=10)
    mag_metrics = photometry_metrics[photometry_metrics["group"] == "mag_true_vs_reference_mag"]
    top_mag_offsets = _top_metric_rows(mag_metrics, "delta_median", n=10, absolute=True)
    missing = pd.concat([distribution_metrics, photometry_metrics], ignore_index=True)
    missing = missing[missing["status"].astype(str).str.startswith("missing")]
    metallicity_row = distribution_metrics[
        distribution_metrics["quantity"] == "log10_stellar_metallicity"
    ]
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "synthetic_path": str(synthetic_path),
        "reference_path": str(reference_path),
        "reference_kind": str(reference_kind),
        "reference_label": str(reference_label),
        "reference_photometry_units": _reference_photometry_units(reference, bands),
        "out_dir": str(out_dir),
        "n_synthetic": int(len(synthetic)),
        "n_reference_used": int(len(reference)),
        "max_reference": max_reference,
        "bands": list(bands),
        "parameter_order": list(DIFFSKY_BASIC_PARAMETER_NAMES),
        "interpretation": (
            "Population sanity comparison only: reference photometry can come from "
            "HLTDS, FS2, or another survey product, while synthetic photometry is "
            "euclid_dsps closure photometry."
        ),
        "sample_warning": (
            "Synthetic sample has fewer than 1000 rows; use this only as a pipeline "
            "smoke diagnostic, not a FENIKS calibration conclusion."
            if len(synthetic) < 1000
            else ""
        ),
        "top_latent_ks": top_latent_ks,
        "top_latent_wasserstein": top_latent_w1,
        "top_mag_median_offsets": top_mag_offsets,
        "missing_metric_count": int(len(missing)),
        "missing_metrics": missing[
            ["group", "quantity", "synthetic_column", "reference_column", "status"]
        ].head(50).to_dict(orient="records"),
        "metallicity_status": (
            metallicity_row.iloc[0].to_dict() if len(metallicity_row) else {}
        ),
        "mass_threshold_fractions": _mass_threshold_fractions(
            synthetic,
            reference,
            proposal_metrics,
        ),
        "correlation_status": correlation_payload.get("status"),
        "correlation_frobenius_error": correlation_payload.get(
            "correlation_frobenius_error"
        ),
        "correlation_mean_abs_error": correlation_payload.get(
            "correlation_mean_abs_error"
        ),
        "plot_paths": [str(path) for path in plot_paths],
    }


def _markdown_report(summary: dict[str, Any]) -> str:
    reference_label = str(summary.get("reference_label") or "Reference")
    lines = [
        f"# FENIKS DSPS-Closure vs {reference_label} Diagnostic",
        "",
        "## Inputs",
        "",
        f"- Synthetic catalog: `{summary['synthetic_path']}`",
        f"- Reference catalog: `{summary['reference_path']}`",
        f"- Reference kind: `{summary.get('reference_kind', 'unknown')}`",
        f"- Reference label: {reference_label}",
        f"- Synthetic rows: {summary['n_synthetic']}",
        f"- Reference rows used: {summary['n_reference_used']}",
        "",
        "## Interpretation",
        "",
        (
            "This report compares population and photometry distributions. It is not an "
            "exact photometric closure test, because the reference photometry is the "
            "external survey-product photometry while the synthetic catalog uses the "
            "euclid_dsps forward model for closure fluxes."
        ),
    ]
    phot_units = summary.get("reference_photometry_units") or {}
    if phot_units:
        converted = [
            f"{band}: {meta.get('mag_column')} from {meta.get('flux_column')}"
            for band, meta in phot_units.items()
            if meta.get("mag_from_flux")
        ]
        if converted:
            lines.extend(["", "Reference flux-to-AB conversions:", ""])
            lines.extend(f"- {item}" for item in converted[:12])
    if summary.get("sample_warning"):
        lines.extend(["", f"Warning: {summary['sample_warning']}"])
    lines.extend(["", "## Mass Threshold Fractions", ""])
    for row in summary.get("mass_threshold_fractions", []):
        lines.append(
            "- "
            f"logsm >= {row['threshold']}: "
            f"synthetic={_format_value(row.get('synthetic_fraction'))}, "
            f"reference={_format_value(row.get('reference_fraction'))}, "
            f"proposal_weighted={_format_value(row.get('proposal_weighted_fraction'))}"
        )
    lines.extend(["", "## Largest Latent KS Distances", ""])
    lines.extend(_metric_bullets(summary.get("top_latent_ks", []), "ks"))
    lines.extend(["", "## Largest Median Magnitude Offsets", ""])
    lines.extend(_metric_bullets(summary.get("top_mag_median_offsets", []), "delta_median"))
    lines.extend(["", "## Correlations", ""])
    lines.append(f"- Status: {summary.get('correlation_status')}")
    if summary.get("correlation_frobenius_error") is not None:
        lines.append(
            "- Frobenius error: "
            f"{_format_value(summary.get('correlation_frobenius_error'))}"
        )
    if summary.get("missing_metric_count"):
        lines.extend(["", "## Missing Or Non-comparable Metrics", ""])
        for row in summary.get("missing_metrics", [])[:20]:
            lines.append(
                "- "
                f"{row['group']}:{row['quantity']} "
                f"({row['synthetic_column']} vs {row['reference_column']}): "
                f"{row['status']}"
            )
    lines.extend(
        [
            "",
            "## Output Files",
            "",
            "- `comparison_summary.json`",
            "- `distribution_metrics.csv`",
            "- `photometry_metrics.csv`",
            "- `correlation_metrics.json`",
            "- `proposal_weighted_metrics.csv` when `--proposal-dir` is provided",
            "- `plots/` when matplotlib is available and plotting is enabled",
            "",
        ]
    )
    return "\n".join(lines)


def _mass_threshold_fractions(
    synthetic: pd.DataFrame,
    reference: pd.DataFrame,
    proposal_metrics: pd.DataFrame,
) -> list[dict[str, Any]]:
    syn = _finite_numeric(synthetic["logsm_true"]) if "logsm_true" in synthetic else np.asarray([])
    ref = _finite_numeric(reference["logsm_true"]) if "logsm_true" in reference else np.asarray([])
    proposal_logsm = (
        proposal_metrics[proposal_metrics["quantity"] == "logsm"].iloc[0].to_dict()
        if not proposal_metrics.empty
        and "quantity" in proposal_metrics
        and np.any(proposal_metrics["quantity"] == "logsm")
        else {}
    )
    rows: list[dict[str, Any]] = []
    for threshold in (5.0, 7.0, 8.0, 9.0, 10.0):
        weighted_fraction = np.nan
        if proposal_logsm:
            weighted_fraction = _proposal_weight_fraction_above(
                proposal_metrics,
                threshold,
            )
        rows.append(
            {
                "threshold": threshold,
                "synthetic_fraction": (
                    float(np.mean(syn >= threshold)) if syn.size else np.nan
                ),
                "reference_fraction": (
                    float(np.mean(ref >= threshold)) if ref.size else np.nan
                ),
                "proposal_weighted_fraction": weighted_fraction,
            }
        )
    return rows


def _proposal_weight_fraction_above(
    proposal_metrics: pd.DataFrame,
    threshold: float,
) -> float:
    row = proposal_metrics[proposal_metrics["quantity"] == "logsm"]
    if row.empty:
        return np.nan
    return float(row.iloc[0].get(f"weighted_fraction_ge_{threshold:g}", np.nan))


def _metric_bullets(rows: Sequence[dict[str, Any]], metric: str) -> list[str]:
    if not rows:
        return ["- No finite metrics available."]
    output = []
    for row in rows[:10]:
        output.append(
            "- "
            f"{row['quantity']}: {metric}={_format_value(row.get(metric))}, "
            f"synthetic_median={_format_value(row.get('synthetic_median'))}, "
            f"reference_median={_format_value(row.get('reference_median'))}"
        )
    return output


def _format_value(value: Any) -> str:
    if value is None:
        return "n/a"
    try:
        number = float(value)
    except (TypeError, ValueError):
        return str(value)
    if not np.isfinite(number):
        return "n/a"
    return f"{number:.6g}"


def _write_json(path: Path, payload: Any) -> None:
    path.write_text(
        json.dumps(_jsonable(payload), indent=2, sort_keys=False, allow_nan=False),
        encoding="utf-8",
    )


def _jsonable(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(key): _jsonable(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_jsonable(item) for item in value]
    if isinstance(value, np.ndarray):
        return _jsonable(value.tolist())
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        value = float(value)
    if isinstance(value, float):
        return value if np.isfinite(value) else None
    if isinstance(value, Path):
        return str(value)
    return value


def _slug(label: str) -> str:
    allowed = []
    for char in label.lower():
        if char.isalnum():
            allowed.append(char)
        else:
            allowed.append("_")
    return "_".join("".join(allowed).split("_"))
