extends: popcosmos_binned.yaml

model:
    ssp_model: compressed_basis
    compressed_ssp_path: Data/popcosmos_chabrier_stellar_ssp_basis_k64_coeff16.h5
    nebular_model: compressed_gas_grid
    compressed_gas_grid_path: Data/popcosmos_chabrier_gas_grid_basis_k64_mixed16.h5
    agn_model: compressed_fsps_component_grid
    compressed_agn_component_grid_path: Data/popcosmos_chabrier_agn_component_basis_k12_fagnlinear_coeff16.h5
