#!/bin/bash
set -Eeuo pipefail

REPO_DIR="${REPO_DIR:-$PWD}"
BENCHMARK_ENV="${1:-outputs/logs/feniks_sc_drws_population_projection_benchmark_latest.env}"
CACHE_ROOT="${CACHE_ROOT:-${SCRATCH:?Set SCRATCH}/feniks_sc_drws_runtime}"
BASELINE_ENV="${BASELINE_ENV:-outputs/logs/feniks_sc_drws_full_test_posterior_latest.env}"

cd "$REPO_DIR"
REPO_DIR="$(pwd -P)"
test -s "$BENCHMARK_ENV" || {
  echo "[full-test-posterior][error] missing benchmark env: $BENCHMARK_ENV" >&2
  exit 2
}
source "$BENCHMARK_ENV"
BASELINE_ROOT="${BASELINE_ROOT:-$RECOVERY_ROOT/frozen_parent_npe_current_q_baseline_v1}"
FULL_ROOT="$BASELINE_ROOT/full_test_k256"
SUPPORT_ROOT="$BASELINE_ROOT/support_k1024"
FULL_ENV="$BASELINE_ROOT/full_test.env"
SUPPORT_ENV="$BASELINE_ROOT/support.env"
mkdir -p "$BASELINE_ROOT" outputs/logs

if [[ ! -s "$FULL_ENV" ]]; then
  POSTERIOR_ROOT="$FULL_ROOT" \
  POSTERIOR_LOG_ROOT="$CACHE_ROOT/slurm_logs/$(basename "$BASELINE_ROOT")-full" \
  POSTERIOR_ENV="$FULL_ENV" \
  POSTERIOR_OBJECTS=4706 POSTERIOR_SHARDS=32 POSTERIOR_MAX_PARALLEL=16 \
  POSTERIOR_PANELS=12 POSTERIOR_DRAWS=256 POSTERIOR_RESAMPLE_DRAWS=64 \
  POSTERIOR_OBJECT_BATCH_SIZE=16 POSTERIOR_PRIOR_DRAWS=512 \
  POSTERIOR_MODEL_RECEIPT= \
  REPO_DIR="$REPO_DIR" CACHE_ROOT="$CACHE_ROOT" \
    bash scripts/submit_feniks_sc_drws_population_posterior.sh "$BENCHMARK_ENV"
fi
source "$FULL_ENV"
BASELINE_FULL_INFERENCE_JOB="$INFERENCE_JOB"
BASELINE_FULL_FINAL_JOB="$FINAL_JOB"
BASELINE_FULL_JOBS="$ALL_JOBS"

if [[ ! -s "$SUPPORT_ENV" ]]; then
  POSTERIOR_ROOT="$SUPPORT_ROOT" \
  POSTERIOR_LOG_ROOT="$CACHE_ROOT/slurm_logs/$(basename "$BASELINE_ROOT")-support" \
  POSTERIOR_ENV="$SUPPORT_ENV" \
  POSTERIOR_OBJECTS=512 POSTERIOR_SHARDS=32 POSTERIOR_MAX_PARALLEL=16 \
  POSTERIOR_PANELS=12 POSTERIOR_DRAWS=1024 POSTERIOR_RESAMPLE_DRAWS=256 \
  POSTERIOR_OBJECT_BATCH_SIZE=8 POSTERIOR_PRIOR_DRAWS=512 \
  POSTERIOR_MODEL_RECEIPT= \
  REPO_DIR="$REPO_DIR" CACHE_ROOT="$CACHE_ROOT" \
    bash scripts/submit_feniks_sc_drws_population_posterior.sh "$BENCHMARK_ENV"
fi
source "$SUPPORT_ENV"
BASELINE_SUPPORT_INFERENCE_JOB="$INFERENCE_JOB"
BASELINE_SUPPORT_FINAL_JOB="$FINAL_JOB"
BASELINE_SUPPORT_JOBS="$ALL_JOBS"

ALL_JOBS="$BASELINE_FULL_JOBS,$BASELINE_SUPPORT_JOBS"
printf 'export BASELINE_ROOT=%q\nexport BASELINE_FULL_ROOT=%q\nexport BASELINE_SUPPORT_ROOT=%q\nexport BASELINE_FULL_ENV=%q\nexport BASELINE_SUPPORT_ENV=%q\nexport BASELINE_FULL_INFERENCE_JOB=%q\nexport BASELINE_FULL_FINAL_JOB=%q\nexport BASELINE_SUPPORT_INFERENCE_JOB=%q\nexport BASELINE_SUPPORT_FINAL_JOB=%q\nexport ALL_JOBS=%q\nexport BENCHMARK_ENV=%q\n' \
  "$BASELINE_ROOT" "$FULL_ROOT" "$SUPPORT_ROOT" "$FULL_ENV" "$SUPPORT_ENV" \
  "$BASELINE_FULL_INFERENCE_JOB" "$BASELINE_FULL_FINAL_JOB" \
  "$BASELINE_SUPPORT_INFERENCE_JOB" "$BASELINE_SUPPORT_FINAL_JOB" \
  "$ALL_JOBS" "$BENCHMARK_ENV" > "$BASELINE_ENV"

echo "baseline_full_job=$BASELINE_FULL_INFERENCE_JOB -> $BASELINE_FULL_FINAL_JOB"
echo "baseline_support_job=$BASELINE_SUPPORT_INFERENCE_JOB -> $BASELINE_SUPPORT_FINAL_JOB"
echo "baseline_root=$BASELINE_ROOT"
echo "latest_env=$BASELINE_ENV"
