#!/bin/bash
set -Eeuo pipefail
cd "${REPO_DIR:-$PWD}"
SOURCE_ENV="${1:?provide balanced_npe_latest.env}"
NIGHT_ROOT="${2:?provide completed precision_night root}"
NEW_ROOT="${3:?provide NEW local diagnostic root}"
unset LOCAL_VI_GRADIENT_ISOLATION LOCAL_VI_REDSHIFT_DECOMPOSITION LOCAL_VI_PHOTOMETRY_REFERENCE
unset LOCAL_VI_FULL_DECODER_REFERENCE LOCAL_VI_MDF_PRECISION_REFERENCE
unset LOCAL_VI_TARGET_RESOLUTION_REFERENCE LOCAL_VI_REDSHIFT_PRECISION_REFERENCE
unset LOCAL_VI_PRECISION_NIGHT_REFERENCE DIAGNOSTIC_LOG_ROOT
export LOCAL_VI_QUALIFIED_NIGHT_ROOT="$NIGHT_ROOT"
export DIAGNOSTIC_ROOT="$NEW_ROOT"
export LOCAL_VI_OBJECTS=8 LOCAL_VI_STEPS=64 LOCAL_VI_DRAWS=128 LOCAL_VI_ARM=C
exec bash scripts/submit_feniks_sc_drws_local_vi_diagnostic.sh "$SOURCE_ENV"
