#!/usr/bin/env python3
"""One gated population marginal-VI M-step from frozen direct-q banks."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import pandas as pd

from euclid_dsps.amortized.config import require_amortized_dependencies
from euclid_dsps.amortized.elbo import AmortizedModel
from euclid_dsps.amortized.features import read_feature_stats
from euclid_dsps.amortized.latent import latent_spec_from_config, theta_to_x
from euclid_dsps.amortized.npe_validation import assert_truth_free_columns
from euclid_dsps.amortized.population_vem import sha256_file
from euclid_dsps.amortized.population_vi import (
    frozen_proposal_population_objective,
    population_prior_value_and_grad,
)
from euclid_dsps.amortized.posthoc_calibration import load_posterior_bank
from euclid_dsps.amortized.train import (
    _selection_correction_runtime_config,
    _selection_log_beta_from_prior_samples,
    load_checkpoint,
    save_checkpoint,
)
from euclid_dsps.config import load_config
from euclid_dsps.io import ensure_dir, write_json
from euclid_dsps.model import dynamic_model_args, load_context

eqx, optax = require_amortized_dependencies()


def _validate_bank_provenance(path: Path, expected_checkpoint_sha256: str) -> dict:
    root = path.resolve()
    if not root.is_dir():
        raise ValueError(
            "population VI requires an inference directory with provenance, "
            f"not a bare posterior table: {root}"
        )
    summary_path = root / "inference_summary.json"
    if not summary_path.is_file() or summary_path.stat().st_size <= 0:
        raise FileNotFoundError(summary_path)
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    if summary.get("complete") is not True:
        raise ValueError(f"population q bank is not complete: {root}")
    if summary.get("truth_used_for_inference_or_checkpoint_selection") is not False:
        raise ValueError(f"population q bank is not truth-free: {root}")
    checkpoint = Path(summary["checkpoint"]).resolve()
    actual = sha256_file(checkpoint)
    if actual != str(expected_checkpoint_sha256):
        raise ValueError(
            "population q bank was generated by a different posterior: "
            f"expected={expected_checkpoint_sha256}, actual={actual}"
        )
    return {
        "root": str(root),
        "inference_summary": str(summary_path),
        "inference_summary_sha256": sha256_file(summary_path),
        "posterior_checkpoint": str(checkpoint),
        "posterior_checkpoint_sha256": actual,
        "truth_used": False,
    }


def _tensor_bank(
    path: Path,
    config: dict,
    expected_objects: int,
    expected_checkpoint_sha256: str,
):
    provenance = _validate_bank_provenance(path, expected_checkpoint_sha256)
    bank = load_posterior_bank(path)
    frame = bank.frame.copy()
    assert_truth_free_columns(frame.columns)
    identity = bank.identity_column
    groups = list(frame.groupby(identity, sort=True))
    if len(groups) != int(expected_objects):
        raise ValueError(
            f"population bank has {len(groups)} objects, expected {expected_objects}; "
            "easy-object filtering is forbidden"
        )
    counts = {len(group) for _, group in groups}
    if len(counts) != 1 or min(counts) < 2:
        raise ValueError("population bank requires one common K >= 2")
    spec = latent_spec_from_config(config)
    theta = []
    loglike = []
    logproposal = []
    identities = []
    for value, group in groups:
        group = group.sort_values("sample_id")
        theta.append(group.loc[:, spec.names].to_numpy(float))
        loglike.append(pd.to_numeric(group["loglike"], errors="raise").to_numpy(float))
        logproposal.append(pd.to_numeric(group["logq"], errors="raise").to_numpy(float))
        identities.append(value)
    theta = jnp.asarray(np.stack(theta, axis=1), dtype=jnp.float32)
    particles = theta_to_x(theta, spec)
    return (
        particles,
        jnp.asarray(np.stack(loglike, axis=1), dtype=jnp.float32),
        jnp.asarray(np.stack(logproposal, axis=1), dtype=jnp.float32),
        identities,
        spec,
        provenance,
    )


def _replace_prior(model: AmortizedModel, prior) -> AmortizedModel:
    return AmortizedModel(
        encoder=model.encoder,
        prior=prior,
        sed_scale=model.sed_scale,
        band_calibration=model.band_calibration,
    )


def train(
    *,
    config_path: Path,
    posterior_checkpoint: Path,
    feature_stats_path: Path,
    fit_bank: Path,
    validation_bank: Path,
    readiness_receipt: Path,
    out: Path,
    expected_fit_objects: int,
    expected_validation_objects: int,
    steps: int,
    learning_rate: float,
    selection_reference_samples: int,
    seed: int,
    activate_population_vi: bool,
) -> dict:
    if not activate_population_vi:
        raise ValueError("population VI requires the explicit activation flag")
    ready = json.loads(readiness_receipt.read_text(encoding="utf-8"))
    if ready.get("status") != "PASS" or ready.get("truth_used") is not False:
        raise ValueError("population VI readiness receipt is absent or not passing")
    expected_posterior = ready.get("posterior_checkpoint_sha256")
    if not expected_posterior:
        raise ValueError("population VI readiness receipt is not bound to a posterior")
    actual_posterior = sha256_file(posterior_checkpoint)
    if actual_posterior != expected_posterior:
        raise ValueError(
            "population VI posterior does not match the readiness receipt: "
            f"expected={expected_posterior}, actual={actual_posterior}"
        )
    config = load_config(config_path)
    if (config.get("truth", {}) or {}).get("parameter_columns"):
        raise ValueError("population marginal-VI config exposes catalogue truth")
    population_cfg = dict(config["amortized"].get("population_vi", {}) or {})
    if population_cfg.get("object_subsampling", {}).get("allow_good_ess_filter"):
        raise ValueError("population VI cannot filter the catalogue by ESS")
    if steps <= 0 or selection_reference_samples < 128:
        raise ValueError("steps and selection reference budget must be positive")
    model = load_checkpoint(posterior_checkpoint, config)
    fit_x, fit_loglike, fit_logq, fit_ids, spec, fit_provenance = _tensor_bank(
        fit_bank, config, expected_fit_objects, expected_posterior
    )
    val_x, val_loglike, val_logq, val_ids, validation_spec, val_provenance = (
        _tensor_bank(
            validation_bank,
            config,
            expected_validation_objects,
            expected_posterior,
        )
    )
    if tuple(spec.names) != tuple(validation_spec.names):
        raise ValueError("fit and validation latent parameter orders differ")
    feature_stats = read_feature_stats(feature_stats_path)
    selection_config = dict(config)
    amortized = dict(selection_config["amortized"])
    objective = dict(amortized["objective"])
    selection = dict(objective.get("selection_correction", {}) or {})
    selection.update(
        {
            "enabled": True,
            "band": "lsst_r",
            "max_mag_ab": 29.0,
            "n_prior_samples": int(selection_reference_samples),
            "prior_sample_batch_size": min(256, int(selection_reference_samples)),
            "common_random_numbers": True,
        }
    )
    objective["selection_correction"] = selection
    amortized["objective"] = objective
    selection_config["amortized"] = amortized
    selection_runtime = _selection_correction_runtime_config(
        selection_config, feature_stats
    )
    context = load_context(config)
    model_args = dynamic_model_args(context)
    reference_x = jax.lax.stop_gradient(
        model.prior.sample(
            jax.random.PRNGKey(int(seed) + 101),
            int(selection_reference_samples),
        )
    )
    reference_logprior = jax.lax.stop_gradient(model.prior.log_prob(reference_x))
    reference_logbeta = jax.lax.stop_gradient(
        _selection_log_beta_from_prior_samples(
            model,
            reference_x,
            spec,
            context,
            model_args,
            spec.names,
            {"calibration": config.get("calibration", {}) or {}},
            selection_runtime,
        )
    )

    def log_alpha(candidate):
        log_weight = reference_logbeta + candidate.log_prob(reference_x)
        log_weight -= reference_logprior
        return jax.scipy.special.logsumexp(log_weight) - jnp.log(
            jnp.asarray(log_weight.size, dtype=log_weight.dtype)
        )

    initial_alpha_logweight = np.asarray(jax.device_get(reference_logbeta), dtype=float)
    initial_alpha_weight = np.exp(initial_alpha_logweight)
    alpha_mean = float(np.mean(initial_alpha_weight))
    alpha_relative_mc_error = float(
        np.std(initial_alpha_weight, ddof=1)
        / np.sqrt(len(initial_alpha_weight))
        / max(alpha_mean, 1.0e-30)
    )
    maximum_alpha_error = float(
        population_cfg["selection"].get("maximum_relative_mc_error", 0.02)
    )
    if alpha_relative_mc_error > maximum_alpha_error:
        raise ValueError(
            "selection alpha reference is too noisy: "
            f"{alpha_relative_mc_error:.4g} > {maximum_alpha_error:.4g}"
        )
    prior = model.prior
    optimizer = optax.chain(
        optax.clip_by_global_norm(1.0),
        optax.adam(float(learning_rate)),
    )
    optimizer_state = optimizer.init(eqx.filter(prior, eqx.is_inexact_array))
    output = ensure_dir(out)
    rows = []
    best_prior = prior
    best_validation_loss = np.inf
    minimum_ess = float(
        population_cfg["technical_gates"]["minimum_median_ess_fraction"]
    )
    maximum_p90_weight = float(
        population_cfg["technical_gates"]["maximum_p90_raw_weight"]
    )
    for step in range(1, int(steps) + 1):
        loss, grads = population_prior_value_and_grad(
            prior,
            fit_x,
            fit_loglike,
            fit_logq,
            log_alpha,
        )
        finite = bool(np.isfinite(float(np.asarray(jax.device_get(loss)))))
        finite &= all(
            bool(np.all(np.isfinite(np.asarray(jax.device_get(leaf)))))
            for leaf in jax.tree_util.tree_leaves(eqx.filter(grads, eqx.is_array))
        )
        if not finite:
            raise ValueError(f"non-finite population objective at step {step}")
        updates, proposed_state = optimizer.update(
            grads,
            optimizer_state,
            eqx.filter(prior, eqx.is_inexact_array),
        )
        proposed = eqx.apply_updates(prior, updates)
        proposed_log_alpha = log_alpha(proposed)
        fit_terms = frozen_proposal_population_objective(
            proposed, fit_x, fit_loglike, fit_logq, proposed_log_alpha
        )
        val_terms = frozen_proposal_population_objective(
            proposed, val_x, val_loglike, val_logq, proposed_log_alpha
        )
        fit_ess = float(
            np.median(np.asarray(jax.device_get(fit_terms.object_ess_fraction)))
        )
        val_ess = float(
            np.median(np.asarray(jax.device_get(val_terms.object_ess_fraction)))
        )
        fit_p90_weight = float(
            np.quantile(
                np.asarray(jax.device_get(fit_terms.object_maximum_weight)), 0.90
            )
        )
        val_p90_weight = float(
            np.quantile(
                np.asarray(jax.device_get(val_terms.object_maximum_weight)), 0.90
            )
        )
        alpha_logweight = np.asarray(
            jax.device_get(
                reference_logbeta
                + proposed.log_prob(reference_x)
                - reference_logprior
            ),
            dtype=float,
        )
        alpha_shifted = np.exp(alpha_logweight - np.max(alpha_logweight))
        alpha_relative_error = float(
            np.std(alpha_shifted, ddof=1)
            / np.sqrt(len(alpha_shifted))
            / max(float(np.mean(alpha_shifted)), 1.0e-30)
        )
        support_ok = min(fit_ess, val_ess) >= minimum_ess
        support_ok &= max(fit_p90_weight, val_p90_weight) <= maximum_p90_weight
        support_ok &= alpha_relative_error <= maximum_alpha_error
        all_objects_finite = bool(
            np.all(np.asarray(jax.device_get(fit_terms.object_finite)))
        )
        all_objects_finite &= bool(
            np.all(np.asarray(jax.device_get(val_terms.object_finite)))
        )
        applied = bool(support_ok and all_objects_finite)
        if applied:
            prior = proposed
            optimizer_state = proposed_state
        validation_loss = float(np.asarray(jax.device_get(val_terms.loss)))
        if applied and validation_loss < best_validation_loss:
            best_validation_loss = validation_loss
            best_prior = prior
        rows.append(
            {
                "step": step,
                "fit_loss": float(np.asarray(jax.device_get(fit_terms.loss))),
                "validation_loss": validation_loss,
                "fit_median_ess_fraction": fit_ess,
                "validation_median_ess_fraction": val_ess,
                "fit_p90_maximum_weight": fit_p90_weight,
                "validation_p90_maximum_weight": val_p90_weight,
                "selection_alpha_relative_mc_error": alpha_relative_error,
                "all_objects_finite": all_objects_finite,
                "update_applied": applied,
                "log_alpha": float(np.asarray(jax.device_get(proposed_log_alpha))),
            }
        )
        if not applied:
            break
    if not np.isfinite(best_validation_loss):
        raise ValueError("no population prior update passed the global support gate")
    pd.DataFrame(rows).to_csv(output / "population_marginal_vi_log.csv", index=False)
    updated_model = _replace_prior(model, best_prior)
    checkpoint = output / "population_mstep.eqx"
    save_checkpoint(
        checkpoint,
        updated_model,
        config=config,
        latent_spec=spec,
        feature_stats=feature_stats,
        epoch=len(rows),
        metric=best_validation_loss,
        metric_name="truth_free_validation_negative_marginal_log_likelihood",
    )
    receipt = {
        "status": "COMPLETE",
        "method": "fixed_direct_q_population_marginal_vi_mstep_v1",
        "checkpoint": str(checkpoint.resolve()),
        "checkpoint_sha256": sha256_file(checkpoint),
        "source_posterior_checkpoint": str(posterior_checkpoint.resolve()),
        "source_posterior_checkpoint_sha256": sha256_file(posterior_checkpoint),
        "readiness_receipt": str(readiness_receipt.resolve()),
        "readiness_receipt_sha256": sha256_file(readiness_receipt),
        "fit_bank": fit_provenance,
        "validation_bank": val_provenance,
        "fit_objects": len(fit_ids),
        "validation_objects": len(val_ids),
        "proposal_frozen_within_mstep": True,
        "complete_q_density_used": True,
        "good_ess_object_filter_used": False,
        "selection": {
            "event": "noisy_lsst_r_ab_lt_29",
            "common_alpha": True,
            "estimator": "fixed_reference_direct_importance",
            "reference_samples": int(selection_reference_samples),
            "relative_mc_error_initial": alpha_relative_mc_error,
            "maximum_relative_mc_error": maximum_alpha_error,
        },
        "candidate_support_contract": {
            "minimum_median_ess_fraction": minimum_ess,
            "maximum_p90_raw_weight": maximum_p90_weight,
            "pareto_gate_source": "pre-update POPULATION_VI_READY.json at K1024",
            "candidate_bank_draws": int(fit_x.shape[0]),
        },
        "steps_attempted": len(rows),
        "steps_applied": int(sum(row["update_applied"] for row in rows)),
        "best_validation_loss": best_validation_loss,
        "next_required_stage": "adapt_q_to_updated_prior_before_another_mstep",
        "truth_used": False,
        "scientific_promotion": False,
    }
    write_json(output / "POPULATION_MSTEP_COMPLETE.json", receipt)
    return receipt


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", dest="config_path", type=Path, required=True)
    parser.add_argument("--posterior-checkpoint", type=Path, required=True)
    parser.add_argument(
        "--feature-stats", dest="feature_stats_path", type=Path, required=True
    )
    parser.add_argument("--fit-bank", type=Path, required=True)
    parser.add_argument("--validation-bank", type=Path, required=True)
    parser.add_argument("--readiness-receipt", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--expected-fit-objects", type=int, required=True)
    parser.add_argument("--expected-validation-objects", type=int, required=True)
    parser.add_argument("--steps", type=int, default=32)
    parser.add_argument("--learning-rate", type=float, default=1.0e-5)
    parser.add_argument("--selection-reference-samples", type=int, default=16384)
    parser.add_argument("--seed", type=int, default=260906)
    parser.add_argument("--activate-population-vi", action="store_true")
    args = parser.parse_args()
    print(json.dumps(train(**vars(args)), indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
